<a href="https://colab.research.google.com/github/iam-sarthak/BigData_MCA/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
array = np.array([1, 2, 3, 6, 4, 5])

res = np.flip(array)

# printing result
print("ans", str(res))

ans [5 4 6 3 2 1]


In [3]:
array = np.array([[1, 2], [3, 4]])
arr = np.array([[1, 2], [3, 4]])

comparison = array == arr
rarrays = comparison.all()

print(rarrays)

True


In [4]:
arr = np.array([1,2,2,3,4,3,5])
print("array:")
print(arr)

print("Most frequent value in array:")
print(np.bincount(arr).argmax())

array:
[1 2 2 3 4 3 5]
Most frequent value in array:
2


In [5]:
arr = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = np.sum(arr)
rows = np.sum(arr, axis=1)

cols = np.sum(arr, axis=0)

print("Matrix:")
print(arr)

print("\ni. Sum of all elements:", total_sum)

print("\nii. Sum of all elements row-wise:")
print(rows)

print("\niii. Sum of all elements column-wise:")
print(cols)

Matrix:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

i. Sum of all elements: 45

ii. Sum of all elements row-wise:
[[14]
 [16]
 [15]]

iii. Sum of all elements column-wise:
[[20  9 16]]
